# Generated by Django 4.1.3 on 2023-02-13 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_speakers_sponsers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='speakers',
            name='profile_img',
            field=models.ImageField(upload_to=''),
        ),
    ]
